using ResearchXBRL.CrossCuttingInterest.Extensions;
using System;
using System.Linq;
using System.Xml;
using Xunit;

namespace ResearchXBRL.Tests.ResearchXBRL.CrossCuttingInterest.Extensions
{
    public sealed class XmlNodeExtensionsTests
    {
        public sealed class GetChildNodesTests
        {
            [Fact]
            public void 全ての子要素を列挙する()
            {
                // arrange
                var sampleAttributes = Enumerable.Repeat("sample", 3).ToArray();
                var targetId = "test-main";
                var xml = $@"
<!DOCTYPE root [
    <!ELEMENT root ANY>
    <!ELEMENT testbase ANY>
    <!ATTLIST testbase SSN ID #REQUIRED>]>
<!-- Generated by PRONEXUS WORKS -->
<root> 
    <testbase SSN=""{targetId}"" link=""http://example.com"">
      <link type=""{sampleAttributes[0]}"" />
      <link type=""{sampleAttributes[1]}"" />
      <link type=""{sampleAttributes[2]}"" />
    </testbase>
</root>";
                var xmlDocument = CreateXMLObject(xml);

                // act
                var acutal = xmlDocument
                    .GetElementById("test-main")?
                    .GetChildNodes()
                    .ToArray()
                    ?? throw new Exception("要素取得失敗");

                // assert
                Assert.Equal(3, acutal.Length);
                Assert.Equal(sampleAttributes[0], acutal[0].Attributes?["type"]?.Value);
                Assert.Equal(sampleAttributes[1], acutal[1].Attributes?["type"]?.Value);
                Assert.Equal(sampleAttributes[2], acutal[2].Attributes?["type"]?.Value);
            }
        }

        public sealed class GetAttributeValueTests
        {
            [Fact]
            public void 指定した属性名属性値を取得する()
            {
                // arrange
                var targetId = "test-main";
                var attribteName = "type";
                var expectedAttributeValue = "sample1";
                var xml = $@"
<!DOCTYPE root [
    <!ELEMENT root ANY>
    <!ELEMENT test ANY>
    <!ATTLIST test SSN ID #REQUIRED>]>
<!-- Generated by PRONEXUS WORKS -->
<root> 
    <testbase link=""http://example.com"">
      <test SSN=""{targetId}"" {attribteName}=""{expectedAttributeValue}"" />
      <test {attribteName}=""sample2"" />
      <test {attribteName}=""sample3"" />
    </testbase>
</root>";
                var xmlDocument = CreateXMLObject(xml);
                var element = xmlDocument.GetElementById("test-main")
                    ?? throw new Exception("要素取得失敗");

                // act
                var acutal = element.GetAttribute("type");

                // assert
                Assert.Equal(expectedAttributeValue, acutal);
            }
        }

        private static XmlDocument CreateXMLObject(string xml)
        {
            var xmlDocument = new XmlDocument();
            xmlDocument.LoadXml(xml.Trim());
            return xmlDocument;
        }
    }
}
